apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "$(CLOUDFLARE_EMAIL)"
    solvers:
      - dns01:
          cloudflare:
            email: "$(CLOUDFLARE_EMAIL)"
            apiKeySecretRef:
              name: cloudflare
              key: dns-token
        selector:
          dnsZones:
            - 'gelinas.cloud'

env:
  - name: CLOUDFLARE_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: email
