apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd

  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    tls.crt: AgCU6mejn2g+pDIW0h3vONXl0ZRnZI8Oq4CHphSJbZmxshrjFD1u6Z9xFFKVsXkzJ9P8Y2OOIWJYi0d5cWnJFLzTWq6aev5C//dVB3omJzc1yrmTXspYmYHawCwZ4aL4ciY+u0ckhz9F2PQFF9B7h1u0rUnFhc+kkItVEGe8fpqwtfO/mGQErl0dBjsitGYyEcvrm7j5HDQL6I+7BQYfX87f/eLjgPXxcUXX+OWc3PQx/T+P2DCABGiURZSUh6KAnHLRrDm0I9n5mrNyqHiAPsvrNZlWL4kKtpKVpRIATmmktyV6mK2dTFo0Jeaos0Xz+L/6vjFF6+fNKfRUNO5onZwhizvzAPtJm4A1baTVs4Ls0MphNwagncA/xSj9OWO20XXmJQRKySa+I8eUmWUeLX9ocPWlkspHVMJSb0k63yi5h+JeMxv/eDIX2WpOVKeyWLw5XpviuaWoFqZq+naB6OJLvGWk3ObhngOCmRkKmjLicZijJptLaO/8e8Jc8ukv6WRfcy12mpx63Bq4OZC3kRptN/yJbvns3GPjY+919DPps00q3j9+pTeLY/zmOooExscDOLgxzOFZLqbaGreKVtCl5fqrtgXzxmXohFVbDbI0hWARzcbMWeUQEdTdGWNcuFC4p2kVOu5YvYyAmgZJ6jdFBtgl0+c8wlQznmWSe0CaomZm5muBhvC2MxTpa4mCWQ7Yivck60QUMj2s6t6UNt6lyVpFLSwZQR6rWyoD5bU2shixHmojjX7bs4JXfP2hjWEJ9f9uP+bA1Ye2i85WYFUWbCrbHwL15Pq+IWY5aQCU5DkScHmQ2IEBCxWZ5vJrzuuB5u8IWz9uoWrHtQ171kDHU+Eq879Yg+tFRYZdAL4ksG13W8atcHnEOjVmy0E1mJOYGSkIr+w8yQsqriXmicM5Y/rcwpd8QkTvL8DzrTLAcm9lRiV1lE+H7TrmonjJoiKxaAqd4ru+cH0JbjhAZv96uHfkq+N/RoFbqX1+T4sSK2fzt3T8D63UH37LPKPJ72H6qrTfOcgrQo2lSwgg4JCkInnYJ19QvjbG3QtFmroqdgsbmytSJ+1IKD8cM+Nfa25Jj/qYcvxZrN8GMVoFStbu0nqaWneRGoDwffuWKBv5U00TuP++v4CicOoOBHI9ofmGSfVPbh0iP+Pmvp7wDm2zTPt/RismFstgf6gIkK5irTA0+/QCvkidOAdlepg1bN38st9eSLUhlvhTrUzZfAioVwDWnCRdgljrMGtbhd6lGOGel20mBNGM0MEHs+UztWhERqad3/g8Xn9Vpv/vGvra9YWnwxR7YQANKp08Jo/joKNdViTEnM8wb7HDXrILN1YraV95jVj7rNblTrXoZ0GQD13eaNfjzhHeHly51ke3S3TsiCIGyJfIs1Pt0D3kW01BYdiWgxBbqnqE/NiJD1TxKq0Dedp+18pfhsuxTSd7LsConbPGnH9WSrPyef22jxTbUHu2+5dr8UbWAEBgHKmi0p2w43mBFQ==
    tls.key: AgAP8QZIsXzrknfEJLGDng78i/083hVP/eix2uRsnAIt99iaTy8sCfJfiLaB1o6cso+1sZdAI7TXpIuqjtyQB1cKyieU2ynKFyEq5aHSXeY0J2oX7fNpYBDDnSs5lNyRGsrrWwr67BLwQdNaPVZ+5cmV6j+IaRX5d9H/YUBtlfF757l2KK1A5mkf0dIBlYrAAByv8lZkpuwN4aPdMyMoTfAvAVFeqwryqyqIJSEg2oqOn9I06FBcxXQrTBxvvlkWXn0V9iNGLbGDQHV61j4/ruxcUeYhlITkiqzlV5Ln4NyZH+5kknwQLkjZy34zUsNX+fKGILF9detrNr74AUGY6wY6+rWjpD6WOijFoDkQwQxeSu0YvlSG0F30yLmNqBRM/dEvLNTJ/fBYqgKx+1TmxG/SR7ZcDqdfAQcKkSjcgFmz8JqD6LYRBCXO+T8lZWmDJdMNOKSs9G8YxH2iyv6MaFGLHFh7Syvv2Zx2dTcathnFGu+SoEtE9pfXUQN7kOnvT2VVsoBKdLcUPC66lTtyA4Mxh4s/k9um/+zjbJ15O/bePZtABPKYLRzg/VuUYcU2qVu4QvI0iYtU1iWVZhXCmR/T54Vl/36tXDgX7BTgWtA/pog3QLp8QlmR4ny8eH+JcwiOydBNf2l32Uh+2AQSRd89WnIiPVjyY2Maj9oIoyf5DDDckNDWkm1DbrYq9nP4RyDdPprcSYpbpx9juHuUnFMXmqUZgMFRA3tfVaG8dFsOf55N+Sq6ywenWPEsHGPtIJS1WRCxrKzyZBKDkhOvW5dGp99LIxH2/WCfeA+FwPz2jwJnHVop7xTuX6BPxl1T7t2tSrtrKFise7iJMFMTTyTd/Fs11/TwHFnRKkdn9sijtGPz6udOZiVe5DRb1O/Fup7AECkURz9w/nbinQHGb+qfErXLrYIbdqwYOO8kRT4X8E9N9S6rvVtfczeJszkndfayotmqqE6HIwtKP/bUclRF0CniOvnJsrBfjAvOIM6SphhaJA==
  template:
    data: null
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.8.1
        linkerd.io/identity-issuer-expiry: "2026-10-03T15:02:01Z"
      creationTimestamp: null
      labels:
        linkerd.io/control-plane-component: identity
        linkerd.io/control-plane-ns: linkerd
      name: linkerd-trust-anchor
      namespace: linkerd
    type: kubernetes.io/tls
