apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: ingress
spec:
  encryptedData:
    dns-token: AgB/jcUkCIwpfgw+cQNZ5Ua2lhNxEyB5rorWdObcWCGUKXixuWohf3Ye6RFgvM6CeIjQcBC1Xpu4/TzhRfZJBKmCL1Xaldb78n/koltDSZ8Yx96yhaZA4ta9giH3fJi5rkouRjPtyk/tIOHaU4oXm5ziDj51Uuot3c2jFxCP/LR1uZ7oIERy86Ie09KhqceRnL8ezgTQH85Ku+gOtZkYI0VHEXMZcDOfTQe12/Lu73Eo/Aer4POUuvccRb5ha1lRdCs/iddj37m2RxMfkTE0YJCsedF6MSVa0zuGR+rLzV+JXMqsCcR25Y+RiRrY6qQ8WOCBIsjv66J+v5pWC24lqdYNdq0DdtnnFlGUZsUgViEptBhltXxMtRCd07FZs4qt3XuTJzHMz0VtI8fm7cDz/L2jBeTBp7MwQZlJTJZGGImunmPtyaxpSf6OERrHTEfCqbUUv3oB5cy6+YLIXNSurwhAjdHAbZRCfDAWhcmNB8vyEz+TrR7xUM9tmUEw0ElNnyQ+r+Q/tFODe7jSpI38rAcRdoqqwIdm1j5n5lXH7x7i7JXPOBQvZKiCXzeKNH+SM3W14kywd9UuJWqAKoOvcjAkxGd8cY3kilXYZNYvOmntJBASDZxsc1DzgQ4rDim5M1o8dGG0JgYHC0aasEevQ2o49iciRpc7t8lKEqY/Uff94STeMIG2tMRsWuNbLFIhYudZIlDizVvC8rAAisCrF1atkqOHjUKNkNZMQltgvKmhvStRWTSCN/Q7
    email: AgALRyWrKVLZb5yZPc4TuCse/1JoHI4PXyF6UphnLHkYFkMyV/QYDIzA6Hgo8Q4bFJRFNO6iGhQaNsSZ6NQChnjxewZHUCSP3E8LeyuZDz5i0iGqkNqMH1xahTcgZ1KnebsriSFZ9JMqmrVCJs7eFyHb1S0TpluPVZvQJuWanKbL9KLGCEwO8PXYsN70bLeA3Fam0TF90GUpzP4rV4IKBlS+KGvtUcWP1SmpQkWKGreEmT7HaLu87Py5OXxR6vTrgul9zSpRzxtiPZYZj45uEyKF6GY5nKSwIBDgS8tmjyTc4p202bJkk+c46KrhJQ98k0GCwbLW4N24eC8wG2JlHA++u/f11etudJojPKkIKeCDbhBhrtj3kgPeT8/XWmK2A3f66sh3EjD6Uep6xj0Jtgkf1W0SY7ua5qb0I1HgeFwjmiKPF0XCFNy6M5FRFm4JPI4ainJN36jaVIu1agKDLlm9y23v4/y/OjIpdJLuf1h3QtwEnq8/XdkOoadituKfeg7WwES7zGNixRCb/dMMpMGdMP6BzzabRooLJ4SHBtgUJzKjyo8e4yOTYtMumQxBWK/bhhB5t+ENm6sBj3Qfo9tVEA3VNYrLyRHNISQWja/pdnzTQGNrrLVsx1nHTSjBcHQSbfrJczv3MCwRq2uOJ1klaNGjHEbkfid5qurQEiZ/KytWuZo3hoOyI4Ywk/K+YZNkLsDzKWazfReEa/BiyOxr+g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: ingress

