apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: ingress
spec:
  encryptedData:
    dns-token: AgAD7/rTsQUyeT/IjMMqwNpb/yXEmLBOD8vORVh2StnNI0SDqmDwx6Ynva6Cv7P2XCoXNZejGxuNAIOivzgXi317xFCukt7JNs9iVGAx4LoOeKyvH1ZIlyvDWoUOoGcp7rX0vblwVYdR6HkzkAaFP347JBJYgqWKGhVJ5aD3rV0AE4Ynwu32VqT10PhGZVxFHZjqx+cFMh3JfHeHwJtSJM+LynNXBQuBTA7yFMw4t+eVU1wsB8DovvmfcWLj6pfdHQJ0+wRFola/bnbLcwQQ4hoG0WERQw0+X+Lu1TCCc2xiNa6up1C2s8TMl81XAAyEnZinl0xV5vxPmqEzBIC+CWyh6xv0daXtFixWhc+gKr5IGrKBMjTVVEV4+fU2TsxsfLGJ5xHiRUVAyQSYf08vvf5QwodOat2IueL+C/qNBrkjiftKA7426pbmUmZVKGKBtNY3zD9jb81Kp2msK+UQnmoe+O5VeZOllpeYYlUUPF+tkCOwkynybZ2+7z3wOtSLaygn/SiR+gP8x5GanvWioDpd/43yvvfqiDPs0Qgsbxc1Epy5TIbNyNEjsyw5q+JAdW3jJ9SmvHIAmNGHwBpIbLUvJB8/aw82uuIiJ1asVkjy2cziNACWdBBLM3m2S6a3IBuSwdEhYWFeZ7c3IAVuaICIQWkvg9unBgyr/eS1odTxAjV6LVeeum8oWD3b2pfFsRjWyzDpDtb662XzAikWQr53BNz5Qd3R/Mq9nblOxd/2TnfCh1RedHCS
    email: AgCKlUuBvE7iZ+sqXmPa39NUE54Hx5i954lUmUTvxI+i6784crGKaugy/6MnIrzzyeCqIPyGwO9jVW5p9jIPkKoYQqtlIrl85kPHZbRhsXb8cCs9Y4FBij1JHs/9iibuVfS+M2iaoH+qCOi+BSKYSYAPR194z5YFWHAUFKAdb8DsJ1QcJwWCsACNnW4QeNn5lEkMVvc4q6JM6SS0d7DglHKHi0P4gz4mNbcGcpomufQbgrwh9+HFPh7HPhfhaBblVm8gLkMaNLCmbv/55A+kuMN8ZC8qhA85XgOK/RaxmwzsXqCNvNNXgArTbjVCMztr0qtmWFiwrgksr8iLBHEG37D/jzRzjVDerUOtY+hme2ISx1SIWbv6cX+M/M6zCtu2Wda/sJ24k4KMc+MgeMict+aCSOVBCe2UMOx5QsBbTVgzzPMoF0PlMyX1Ptc21DSCCjxLAS7yEcmvUDIQTp4gTSWuEz8b+KrizfB4YwTveaK8oi+EW2oWhfYkHeZXPkxn1hoEsdXJdEfDc8qyp5SqmyTcg7OxRfeUZ1RCFvr+6ZqRLPxetIa/hHxcc+NrCvYl8AN+sWT4LNDzqj/QA8CVqGzYmY5RUqxOYIEdarwtMNTP3c4XAOdB7fYc8swgBxA3+h5yDCf1J7j15JycLg9/eMPwnjkp4MEnsGaFhDfZ1ve6G1ATFboXSX1NbkJLJgoKN0NoMkFgkgHlExino5hvBBNYDQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: ingress
