apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argo-cd-ui-ingressroute.yaml
  - applications/traefik-application.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

namespace: argocd

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argocd
  newTag: 2.2.0-20313adb
